// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: idsvc.proto

package idsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdsvcClient is the client API for Idsvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdsvcClient interface {
	GetId(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type idsvcClient struct {
	cc grpc.ClientConnInterface
}

func NewIdsvcClient(cc grpc.ClientConnInterface) IdsvcClient {
	return &idsvcClient{cc}
}

func (c *idsvcClient) GetId(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/idsvc/GetId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdsvcServer is the server API for Idsvc service.
// All implementations must embed UnimplementedIdsvcServer
// for forward compatibility
type IdsvcServer interface {
	GetId(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedIdsvcServer()
}

// UnimplementedIdsvcServer must be embedded to have forward compatible implementations.
type UnimplementedIdsvcServer struct {
}

func (UnimplementedIdsvcServer) GetId(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetId not implemented")
}
func (UnimplementedIdsvcServer) mustEmbedUnimplementedIdsvcServer() {}

// UnsafeIdsvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdsvcServer will
// result in compilation errors.
type UnsafeIdsvcServer interface {
	mustEmbedUnimplementedIdsvcServer()
}

func RegisterIdsvcServer(s grpc.ServiceRegistrar, srv IdsvcServer) {
	s.RegisterService(&Idsvc_ServiceDesc, srv)
}

func _Idsvc_GetId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdsvcServer).GetId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idsvc/GetId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdsvcServer).GetId(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Idsvc_ServiceDesc is the grpc.ServiceDesc for Idsvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Idsvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idsvc",
	HandlerType: (*IdsvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetId",
			Handler:    _Idsvc_GetId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idsvc.proto",
}
